apiVersion: v1
kind: Service
metadata:
  name: leave-planner-ui-service
  namespace: leave-planner
  labels:
    app: leave-planner
    type: service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
  selector:
    app: leave-planner
    type: ui-pods
---
apiVersion: v1
kind: Service
metadata:
  name: leave-planner-backend-service
  namespace: leave-planner
  labels:
    app: leave-planner
    type: service
spec:
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30002
  selector:
    app: leave-planner
    type: backend-pods
